travis:
  secure:
    BINSTAR_TOKEN: GBWqO62KjFREilzSMgcAc8HmdAHOI6G026wjTGYt8MHIolAs992Pt7b47FnuTam+w+Qrc7+Oaym9omaWVFmLUsHfJ4NMoot+HocDMa3ZyXVMWqlptVgd1BsxAK52eBS5HXJUnqv4kjWy6EkPgZgfBYEDYfaGEfKjy5bR3EACWaSWtF0+dr2cpMHYPjYJ/ZbXSW8AAnDlLIKJ8gSXuGLbHMZ7fma5IDdOZgikzqEVNuGePTe1/h3pycUSusmzwGvIzFjQReHOGslG+gsUaBN5Ox5VTljCCWFWL0DM3hq7rdx07pRnlP07a3nfZjK0BVzLox3HWf/Z1Lw9ba2yW7QnwazBPEhTfQ5gMpmdmzB4ajdmBWkt9NSdwlWieFn5AOUMd5oewL9YmGsljpbp0eU6poJ30zdRzDeLY0qfx1Rl1twYYDeqL8d7c48IlhNIgi8S3UuYbdrkhOJkgtVkpxX826KOlOzAswJSm8VRgUNWXD9YvrtUr76E56bfBJKA8Fp0vSRD5gynBkCz322yew9fdQs2x2SIl3h+xxHOqhgk0RWyCsC0Dvpea2FNd5CoGQsncTwpg7381SC9HZtxzQymN0YftQc80j6sBOqsAS5Ycm3W04EZmNL36476lLzdV5cUfL20qW/JmZEaO5XXlM8d4SYlFuNJnY6z9HgaX0h35qY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
